// Patriot Floor Plan - 4bd · 3 ba · 1 half ba · 3,004 ft²
// Coordinates are in feet, origin at bottom-left of home footprint
// Each room: { id, name, x, y, width, depth, wallHeight, color, floorColor }
// x,y = bottom-left corner in feet from plan origin

export const SCALE = 1; // 1 unit = 1 foot in 3D space

export const defaultRooms = [
  // ---- Main structure ----
  {
    id: "owners-suite",
    name: "Owner's Suite",
    dimensions: "16' x 16'",
    x: 0, y: 26, width: 16, depth: 16,
    wallHeight: 9,
    wallColor: "#f5f5f0",
    floorColor: "#c8a97e",
  },
  {
    id: "bath-owners",
    name: "Bath",
    dimensions: "",
    x: 0, y: 22, width: 8, depth: 4,
    wallHeight: 9,
    wallColor: "#e8f4f8",
    floorColor: "#b0c4d8",
  },
  {
    id: "walk-in-closet",
    name: "Walk-In Closet",
    dimensions: "",
    x: 8, y: 20, width: 10, depth: 8,
    wallHeight: 9,
    wallColor: "#f5f5f0",
    floorColor: "#d4c5a9",
  },
  {
    id: "family-room",
    name: "Family Room",
    dimensions: "19' x 23'",
    x: 14, y: 19, width: 19, depth: 23,
    wallHeight: 9,
    wallColor: "#f8f6f0",
    floorColor: "#c8a97e",
  },
  {
    id: "covered-lanai",
    name: "Covered Lanai",
    dimensions: "",
    x: 14, y: 42, width: 18, depth: 8,
    wallHeight: 9,
    wallColor: "#e8ede8",
    floorColor: "#a0a890",
  },
  {
    id: "dining-room",
    name: "Dining Room",
    dimensions: "14' x 10'",
    x: 32, y: 42, width: 14, depth: 10,
    wallHeight: 9,
    wallColor: "#f8f6f0",
    floorColor: "#c8a97e",
  },
  {
    id: "kitchen",
    name: "Kitchen",
    dimensions: "14' x 17'",
    x: 33, y: 25, width: 14, depth: 17,
    wallHeight: 9,
    wallColor: "#f8f6f0",
    floorColor: "#d4c5a9",
  },
  {
    id: "bedroom2",
    name: "Bedroom 2",
    dimensions: "11' x 12'",
    x: 35, y: 13, width: 11, depth: 12,
    wallHeight: 9,
    wallColor: "#f5f5f0",
    floorColor: "#c8a97e",
  },
  {
    id: "bedroom3",
    name: "Bedroom 3",
    dimensions: "11' x 13'",
    x: 35, y: 0, width: 11, depth: 13,
    wallHeight: 9,
    wallColor: "#f5f5f0",
    floorColor: "#c8a97e",
  },
  {
    id: "bath2",
    name: "Bath 2",
    dimensions: "",
    x: 28, y: 0, width: 7, depth: 13,
    wallHeight: 9,
    wallColor: "#e8f4f8",
    floorColor: "#b0c4d8",
  },
  {
    id: "hvac",
    name: "HVAC",
    dimensions: "",
    x: 28, y: 13, width: 5, depth: 6,
    wallHeight: 9,
    wallColor: "#e0e0e0",
    floorColor: "#c0c0c0",
  },
  {
    id: "study",
    name: "Study",
    dimensions: "12' x 12'",
    x: 14, y: 13, width: 12, depth: 12,
    wallHeight: 9,
    wallColor: "#f5f5f0",
    floorColor: "#c8a97e",
  },
  {
    id: "laundry",
    name: "Laundry",
    dimensions: "",
    x: 14, y: 8, width: 8, depth: 5,
    wallHeight: 9,
    wallColor: "#e8f4f8",
    floorColor: "#b0c4d8",
  },
  {
    id: "foyer",
    name: "Foyer",
    dimensions: "",
    x: 14, y: 3, width: 8, depth: 5,
    wallHeight: 9,
    wallColor: "#f8f6f0",
    floorColor: "#c8a97e",
  },
  {
    id: "powder",
    name: "Pwdr",
    dimensions: "",
    x: 14, y: 0, width: 4, depth: 3,
    wallHeight: 9,
    wallColor: "#e8f4f8",
    floorColor: "#b0c4d8",
  },
  {
    id: "covered-porch",
    name: "Covered Porch",
    dimensions: "",
    x: 18, y: -4, width: 8, depth: 4,
    wallHeight: 9,
    wallColor: "#e8ede8",
    floorColor: "#a0a890",
  },
  {
    id: "garage-2bay",
    name: "2-Bay Garage",
    dimensions: "19' x 20'",
    x: 27, y: -4, width: 19, depth: 20,
    wallHeight: 9,
    wallColor: "#e8e8e0",
    floorColor: "#b0b0a8",
  },
  // ---- Next Gen Suite (highlighted in blue) ----
  {
    id: "nextgen-bedroom",
    name: "Next Gen Bedroom",
    dimensions: "11' x 15'",
    x: 0, y: 8, width: 11, depth: 15,
    wallHeight: 9,
    wallColor: "#e8f0f8",
    floorColor: "#b8cce0",
    isNextGen: true,
  },
  {
    id: "nextgen-lndry",
    name: "Lndry",
    dimensions: "",
    x: 0, y: 6, width: 6, depth: 3,
    wallHeight: 9,
    wallColor: "#dce8f4",
    floorColor: "#b0c8e0",
    isNextGen: true,
  },
  {
    id: "nextgen-bath",
    name: "Bath",
    dimensions: "",
    x: 0, y: 3, width: 6, depth: 3,
    wallHeight: 9,
    wallColor: "#dce8f4",
    floorColor: "#a8c0d8",
    isNextGen: true,
  },
  {
    id: "nextgen-living",
    name: "Next Gen Living",
    dimensions: "10' x 17'",
    x: 0, y: -14, width: 10, depth: 17,
    wallHeight: 9,
    wallColor: "#e8f0f8",
    floorColor: "#b8cce0",
    isNextGen: true,
  },
  {
    id: "kitchenette",
    name: "Kitchenette",
    dimensions: "7' x 13'",
    x: 0, y: -27, width: 7, depth: 13,
    wallHeight: 9,
    wallColor: "#dce8f4",
    floorColor: "#b0c8e0",
    isNextGen: true,
  },
  {
    id: "rec-garage",
    name: "Recreational Garage",
    dimensions: "12' x 10'",
    x: 0, y: -37, width: 12, depth: 10,
    wallHeight: 9,
    wallColor: "#e8e8e0",
    floorColor: "#b0b0a8",
    isNextGen: true,
  },
];

export const furnitureItems = [
  // Living room furniture
  { id: "sofa", name: "Sofa", icon: "🛋️", width: 7, depth: 3, height: 3, color: "#8B7355" },
  { id: "loveseat", name: "Loveseat", icon: "🛋️", width: 5, depth: 3, height: 3, color: "#8B7355" },
  { id: "coffee-table", name: "Coffee Table", icon: "🔲", width: 4, depth: 2, height: 1.5, color: "#6B4226" },
  { id: "armchair", name: "Arm Chair", icon: "🪑", width: 3, depth: 3, height: 3.5, color: "#7A6040" },
  { id: "tv-stand", name: "TV Stand", icon: "📺", width: 5, depth: 1.5, height: 3, color: "#4A3728" },
  { id: "bookshelf", name: "Bookshelf", icon: "📚", width: 3, depth: 1, height: 6, color: "#5C3A1E" },
  // Dining
  { id: "dining-table", name: "Dining Table", icon: "🪑", width: 6, depth: 3, height: 2.5, color: "#8B6914" },
  { id: "dining-chair", name: "Dining Chair", icon: "🪑", width: 1.5, depth: 1.5, height: 3, color: "#6B4C14" },
  // Bedroom
  { id: "king-bed", name: "King Bed", icon: "🛏️", width: 6.5, depth: 6.5, height: 3, color: "#8B7D6B" },
  { id: "queen-bed", name: "Queen Bed", icon: "🛏️", width: 5, depth: 6.5, height: 3, color: "#8B7D6B" },
  { id: "twin-bed", name: "Twin Bed", icon: "🛏️", width: 3.5, depth: 6.5, height: 3, color: "#8B7D6B" },
  { id: "dresser", name: "Dresser", icon: "🗄️", width: 4, depth: 1.5, height: 4, color: "#6B4C14" },
  { id: "nightstand", name: "Nightstand", icon: "🗄️", width: 1.5, depth: 1.5, height: 2, color: "#6B4C14" },
  // Kitchen
  { id: "kitchen-island", name: "Kitchen Island", icon: "🔲", width: 4, depth: 2, height: 3, color: "#C8C8C8" },
  // Office
  { id: "desk", name: "Desk", icon: "🖥️", width: 5, depth: 2.5, height: 2.5, color: "#8B7355" },
  { id: "office-chair", name: "Office Chair", icon: "🪑", width: 2, depth: 2, height: 3.5, color: "#2C2C2C" },
  // Other
  { id: "plant", name: "Plant", icon: "🌿", width: 1.5, depth: 1.5, height: 4, color: "#228B22" },
  { id: "rug", name: "Area Rug", icon: "🟫", width: 6, depth: 4, height: 0.1, color: "#8B4513" },
  { id: "bathtub", name: "Bathtub", icon: "🛁", width: 5, depth: 2.5, height: 2, color: "#FFFFFF" },
  { id: "toilet", name: "Toilet", icon: "🚽", width: 1.5, depth: 2.5, height: 2.5, color: "#FFFFFF" },
  { id: "sink", name: "Sink", icon: "🚿", width: 2, depth: 1.5, height: 3, color: "#FFFFFF" },
];
